/hst:hst/hst:configurations/campaign1/hst:workspace/hst:pages/application-campaign-mainpage:
  jcr:primaryType: hst:component
  hst:lastmodified: 2018-03-06T12:03:15.541-05:00
  hst:referencecomponent: hst:abstractpages/base
  /main:
    jcr:primaryType: hst:component
    hst:template: campaign-campaignpage-main
    /main-container:
      jcr:primaryType: hst:containercomponent
      hst:lastmodified: 2018-03-06T12:05:34.748-05:00
      hst:xtype: hst.vbox
      /campaign-application-form:
        jcr:primaryType: hst:containeritemcomponent
        hst:componentclassname: org.onehippo.forge.pageflow.demo.campaign.components.CampaignApplicationFormComponent
        hst:iconpath: images/campaignbase/catalog-component-icons/campaign-default.png
        hst:label: Campaign Application Form
        hst:template: campaign-application-form
        hst:xtype: hst.item
